#### IT's time to clean our data
##### Our Data is taken from kaggle so there is no such missing and unpredictable values.
##### But there are some unwannted columns that we must have to remove

In [1]:
import pandas as pd
import numpy as np
import confidential_file as paths

tables = {
    'customers': paths.customers,
    'products': paths.products,
    'sales': paths.sales
}

### First we focuses on customers file

In [4]:
tables['customers'].head(10)

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1977-01-13,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1952-01-20,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,26-35,1994-01-09,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00
3,CUST00000004,Aditya Pandey,male,41,36-45,1984-01-12,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,Platinum,5,288324.84
4,CUST00000005,Hina Khan,female,53,46-55,1972-01-15,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,Platinum,4,69265.75
5,CUST00000006,Swati Pandey,female,19,18-25,2006-01-06,swatipandey224@gmail.com,+91-9199445972,Jodhpur,Rajasthan,226445,2024-04-26,Platinum,6,195157.41
6,CUST00000007,Nikhil Iyer,male,34,26-35,1991-01-10,nikhiliyer28@outlook.com,+91-9319135211,Jodhpur,Rajasthan,495420,2024-05-10,Platinum,7,216730.17
7,CUST00000008,Preeti Pandey,female,60,56-65,1965-01-16,preetipandey666@outlook.com,+91-9941630610,Faridabad,Haryana,304884,2024-04-02,Platinum,7,149633.69
8,CUST00000009,Shreya Patel,female,35,26-35,1990-01-10,shreyapatel226@yahoo.com,+91-7662144087,Jalandhar,Punjab,190336,2023-10-03,Platinum,7,339103.94
9,CUST00000010,Omar Mirza,male,42,36-45,1983-01-12,omarmirza829@gmail.com,+91-8249924428,Alwar,Rajasthan,824048,2023-11-22,Platinum,6,192737.10

### All things are done but there are three columns that are showing the birth date, age and age group
### And we need to find the in which basis customer_tier are decided

### Now check the columns for product table

In [5]:
tables['products'].head(10)

,Product_ID,Product_Name,Category,Brand,Original_Price,Discount_Percent,Discount_Amount,Selling_Price,Stock_Quantity,Weight_kg,Avg_Rating,Total_Reviews
0,PROD000001,Samsung Mobile V5,Electronics,Samsung,130561.34,23,30029.11,100532.23,159,2.63,4.49,102
1,PROD000002,HP Laptop V5,Electronics,HP,36494.92,34,12408.27,24086.65,54,4.19,4.32,107
2,PROD000003,boAt Headphones V2,Electronics,boAt,106587.94,42,44766.93,61821.01,638,1.48,4.31,99
3,PROD000004,Noise Watch V7,Electronics,Noise,81275.27,47,38199.38,43075.89,572,3.30,4.42,127
4,PROD000005,Apple iPhone V4,Electronics,Apple,13099.36,43,5632.72,7466.64,865,3.71,4.37,98
5,PROD000006,Levis Jeans V1,Fashion,Levis,3330.44,9,299.74,3030.70,380,2.64,4.47,81
6,PROD000007,Peter England Shirt V8,Fashion,Peter,7504.54,12,900.54,6604.00,800,2.12,4.37,82
7,PROD000008,Nike Shoes V2,Fashion,Nike,7210.81,38,2740.11,4470.70,321,1.71,4.29,104
8,PROD000009,Titan Watch V10,Fashion,Titan,8545.82,48,4101.99,4443.83,266,0.82,4.52,94
9,PROD000010,Puma T-shirt V7,Fashion,Puma,12528.96,35,4385.14,8143.82,834,3.12,4.37,89

### All things look Good

### Move to the Sales table

In [6]:
tables['sales'].head(10)

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.00,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.00,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.00,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.00,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.00,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45
5,ORD0000000006,CUST00033802,PROD000121,2025-09-18,11:56:00,2025-09-23,1,4489.77,4489.77,0.0,...,50.00,4439.77,UPI,Returned,NaN,NaN,Agra,UP,50,46-55
6,ORD0000000007,CUST00027469,PROD001308,2026-03-01,10:32:00,2026-03-05,2,33620.99,67241.98,0.0,...,0.00,67241.98,COD,Processing,NaN,NaN,Dwarka,Delhi,36,36-45
7,ORD0000000008,CUST00017326,PROD001392,2024-06-19,17:46:00,2024-06-23,2,1161.62,2323.24,0.0,...,232.32,2090.92,Credit Card,Delivered,NaN,NaN,Delhi NCR,Delhi,20,18-25
8,ORD0000000009,CUST00009627,PROD001876,2025-02-12,12:19:00,2025-02-15,1,22456.69,22456.69,0.0,...,2245.67,20211.02,Credit Card,Delivered,NaN,NaN,Agra,UP,29,26-35
9,ORD0000000010,CUST00012719,PROD000214,2024-10-19,07:45:00,2024-10-25,1,86647.71,86647.71,0.0,...,0.00,86647.71,UPI,Delivered,5.0,Highly recommended!,Surat,Gujarat,39,36-45

In [7]:
tables['sales'].columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Order_Date', 'Order_Time',
       'Delivery_Date', 'Quantity', 'Unit_Price', 'Order_Value',
       'Shipping_Cost', 'Coupon_Code', 'Coupon_Discount', 'Total_Amount',
       'Payment_Mode', 'Order_Status', 'Rating', 'Review_Text', 'City',
       'State', 'Customer_Age', 'Customer_Age_Group'],
      dtype='str')

In [9]:
tables['sales']['Coupon_Code'].unique()

<StringArray>
[nan, 'FLAT50', 'SAVE10', 'DIWALI100']
Length: 4, dtype: str

In [10]:
tables['sales']['Payment_Mode'].unique()

<StringArray>
['COD', 'UPI', 'Credit Card', 'Debit Card']
Length: 4, dtype: str

In [11]:
tables['sales']['Order_Status'].unique()

<StringArray>
['Delivered', 'Processing', 'Returned', 'Cancelled', 'Shipped']
Length: 5, dtype: str

### There are AGE, State, Customer_Age_Group are available on customer table so we can delete that columns

In [20]:
tables['customers']['Gender'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [13]:
print(tables['customers'].isnull().sum())
print(tables['products'].isnull().sum())
print(tables['sales'].isnull().sum())

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
Age_Group            0
Date_of_Birth        0
Email                0
Phone                0
City                 0
State                0
Pincode              0
Registration_Date    0
Customer_Tier        0
Total_Orders         0
Total_Spent          0
dtype: int64
Product_ID          0
Product_Name        0
Category            0
Brand               0
Original_Price      0
Discount_Percent    0
Discount_Amount     0
Selling_Price       0
Stock_Quantity      0
Weight_kg           0
Avg_Rating          0
Total_Reviews       0
dtype: int64
Order_ID                   0
Customer_ID                0
Product_ID                 0
Order_Date                 0
Order_Time                 0
Delivery_Date              0
Quantity                   0
Unit_Price                 0
Order_Value                0
Shipping_Cost              0
Coupon_Code           199815
Coupon_Discount            0
Total_Amount               0
Payment_Mode               0
Order_Status               0
Rating                129970
Review_Text           129970
City                       0
State                      0
Customer_Age               0
Customer_Age_Group         0
dtype: int64

In [14]:
print(tables['customers'].duplicated().sum())
print(tables['products'].duplicated().sum())
print(tables['sales'].duplicated().sum())

0
0
0

In [16]:
print(tables['customers'].info())
print(tables['products'].info())
print(tables['sales'].info())

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        40000 non-null  str
 1   Customer_Name      40000 non-null  str
 2   Gender             40000 non-null  str
 3   Age                40000 non-null  int64
 4   Age_Group          40000 non-null  str
 5   Date_of_Birth      40000 non-null  str
 6   Email              40000 non-null  str
 7   Phone              40000 non-null  str
 8   City               40000 non-null  str
 9   State              40000 non-null  str
 10  Pincode            40000 non-null  int64
 11  Registration_Date  40000 non-null  str
 12  Customer_Tier      40000 non-null  str
 13  Total_Orders       40000 non-null  int64
 14  Total_Spent        40000 non-null  float64
dtypes: float64(1), int64(3), str(11)
memory usage: 4.6 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_ID        2000 non-null   str
 1   Product_Name      2000 non-null   str
 2   Category          2000 non-null   str
 3   Brand             2000 non-null   str
 4   Original_Price    2000 non-null   float64
 5   Discount_Percent  2000 non-null   int64
 6   Discount_Amount   2000 non-null   float64
 7   Selling_Price     2000 non-null   float64
 8   Stock_Quantity    2000 non-null   int64
 9   Weight_kg         2000 non-null   float64
 10  Avg_Rating        2000 non-null   float64
 11  Total_Reviews     2000 non-null   int64
dtypes: float64(5), int64(3), str(4)
memory usage: 187.6 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_ID            250000 non-null  str
 1   Customer_ID         250000 non-null  str
 2   Product_ID          250000 non-null  str
 3   Order_Date          250000 non-null  str
 4   Order_Time          250000 non-null  str
 5   Delivery_Date       250000 non-null  str
 6   Quantity            250000 non-null  int64
 7   Unit_Price          250000 non-null  float64
 8   Order_Value         250000 non-null  float64
 9   Shipping_Cost       250000 non-null  float64
 10  Coupon_Code         50185 non-null   str
 11  Coupon_Discount     250000 non-null  float64
 12  Total_Amount        250000 non-null  float64
 13  Payment_Mode        250000 non-null  str
 14  Order_Status        250000 non-null  str
 15  Rating              120030 non-null  float64
 16  Review_Text         120030 non-null  str
 17  City                250000 non-null  str
 18  State               250000 non-null  str
 19  Customer_Age        250000 non-null  int64
 20  Customer_Age_Group  250000 non-null  str
dtypes: float64(6), int64(2), str(13)
memory usage: 40.1 MB
None

In [19]:
print(tables['customers'].describe(), "\n")
print(tables['products'].describe(), "\n")
print(tables['sales'].describe())

                Age        Pincode  Total_Orders   Total_Spent
count  40000.000000   40000.000000  40000.000000   40000.00000
mean      35.306225  549135.098375      5.003475  118539.15886
std       12.581443  259430.688860      2.232485  106205.42346
min       18.000000  100010.000000      0.000000       0.00000
25%       26.000000  325689.750000      3.000000   37814.14750
50%       33.000000  547573.500000      5.000000   90059.66000
75%       43.000000  773876.000000      6.000000  169958.41750
max       75.000000  999986.000000     17.000000  890131.55000

       Original_Price  Discount_Percent  Discount_Amount  Selling_Price  \
count     2000.000000       2000.000000       2000.00000     2000.00000
mean     18323.619210         27.471000       5143.28014    13180.33907
std      29472.155725         13.309874       9732.99126    21514.94963
min         52.250000          5.000000          6.29000       26.13000
25%       1522.505000         16.000000        332.26000     1088.03750
50%       4775.355000         27.000000       1154.91500     3543.41500
75%      22358.115000         39.000000       5452.93500    16063.81250
max     149658.640000         50.000000      71289.60000   136973.33000

       Stock_Quantity    Weight_kg   Avg_Rating  Total_Reviews
count     2000.000000  2000.000000  2000.000000    2000.000000
mean       503.479000     2.640980     4.398185      60.015000
std        287.140337     1.373574     0.095983      27.645161
min         10.000000     0.210000     3.910000      15.000000
25%        250.750000     1.430000     4.340000      38.000000
50%        504.500000     2.725000     4.400000      54.000000
75%        749.000000     3.790000     4.460000      78.000000
max       1000.000000     5.000000     4.760000     139.000000

            Quantity     Unit_Price    Order_Value  Shipping_Cost  \
count  250000.000000  250000.000000  250000.000000  250000.000000
mean        1.249580   19202.477645   23967.862192       4.911971
std         0.535689   26720.495176   37629.320529      18.141581
min         1.000000      26.130000      26.130000       0.000000
25%         1.000000    1551.550000    1825.890000       0.000000
50%         1.000000    7208.930000    8411.160000       0.000000
75%         1.000000   24433.270000   28612.810000       0.000000
max         3.000000  136973.330000  410919.990000      90.000000

       Coupon_Discount   Total_Amount         Rating   Customer_Age
count    250000.000000  250000.000000  120030.000000  250000.000000
mean        250.001146   23722.773017       4.399400      35.309416
std        1399.928532   37267.644163       0.663915      12.574524
min           0.000000     -21.560000       3.000000      18.000000
25%           0.000000    1803.900000       4.000000      26.000000
50%           0.000000    8339.490000       4.000000      33.000000
75%           0.000000   28344.920000       5.000000      43.000000
max       41092.000000  410919.990000       5.000000      75.000000

### I analyze everything, all things are perfectly fine.
###### - No negetive values
###### - Data Type is perfect
###### - No Null Values except(coupon code)
###### - No Duplicate Values
###### - Unique Values count are perfect eg.('male', 'female')